[build]
  command = "./gradlew wasmJsBrowserDevelopmentExecutable -PAPI_BASE_URL=$API_BASE_URL --no-configuration-cache --no-daemon"
  publish = "composeApp/build/dist/wasmJs/developmentExecutable"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
